name: ioul
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  audio_video_progress_bar: ^2.0.0
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.2
  archive: ^3.3.9
  flutter_screenutil: ^5.7.0
  flutter_svg: ^1.0.3
  toggle_switch: ^2.1.0
  intl: ^0.17.0
  h3m_shimmer_card: ^0.0.2
  audioplayers: ^5.2.1
  go_router: ^8.0.5
  flutter_native_splash: ^2.2.19
  pinput: ^2.2.31
  cool_dropdown: ^2.1.0
  #mockito: ^5.4.3
  mocktail: ^1.0.1
  animated_custom_dropdown: ^1.5.0
  group_button: ^5.3.0
  intl_phone_field: ^3.2.0
  chips_choice: ^3.0.0
  video_player: ^2.7.0
  flutter_windowmanager: ^0.2.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14

  # flutterwave_standard: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/audio/
    - assets/.env
    - assets/translation/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/interregular.ttf
        - asset: assets/fonts/interlight.ttf
          style: italic
